name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Cargo Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Update README
        if: github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest'
        run: |
          # use release flag since that's built above
          cargo run --release -- -d README.template.md -o README.md

      - name: Push README
        if: github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest'
        uses: test-room-7/action-update-file@v1
        with:
          file-path: README.md
          commit-msg: 'chore: update README from template'
          github-token: ${{ secrets.GITHUB_TOKEN }}